# Generated by Django 3.0.7 on 2020-07-02 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_anuncio', models.CharField(max_length=100)),
                ('fecha_anuncio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono1', models.CharField(max_length=15)),
                ('telefono2', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
                ('nivel_anunciante', models.CharField(max_length=1)),
                ('id_anunciante', models.CharField(max_length=4)),
                ('id_articulo', models.CharField(max_length=5)),
                ('id_negocio', models.CharField(max_length=4)),
                ('id_servicio', models.CharField(max_length=4)),
            ],
        ),
    ]
