# Generated by Django 3.0.7 on 2020-09-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0005_auto_20200709_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_anunciante',
            new_name='anunciante',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_articulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_negocio',
            new_name='negocio',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_servicio',
            new_name='servicio',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publiapp_api.Anuncio'),
        ),
    ]
