# Generated by Django 3.0.7 on 2020-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0006_auto_20200905_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='descripcion_articulo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre_articulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='descripcion_negocio',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='nombre_negocio',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='descripcion_servicio',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre_servicio',
            new_name='nombre',
        ),
    ]
