# Generated by Django 3.0.7 on 2020-09-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0007_auto_20200919_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=800)),
                ('tipoAnuncio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.FloatField(default=0.0)),
                ('monto_promo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='id_resenia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id_resenia',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Negocio',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.AddField(
            model_name='precio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='publiapp_api.Anuncio'),
        ),
        migrations.AddField(
            model_name='detalleanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleAnuncio', to='publiapp_api.Anuncio'),
        ),
        migrations.AddField(
            model_name='detalleanuncio',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publiapp_api.Categoria'),
        ),
        migrations.AddField(
            model_name='detalleanuncio',
            name='id_resenia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publiapp_api.Resenia'),
        ),
    ]
