# Generated by Django 3.0.7 on 2020-09-26 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0010_auto_20200925_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBusqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=30)),
                ('dispositivo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LogContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anuncio', models.CharField(max_length=40)),
                ('dispositivo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nro_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LogDetalleAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anuncio', models.CharField(max_length=40)),
                ('dispositivo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='Ubigeo',
            field=models.ForeignKey(default=685, on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo', to='publiapp_api.Ubigeo'),
            preserve_default=False,
        ),
    ]
