# Generated by Django 3.0.7 on 2020-09-27 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0012_auto_20200926_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleanuncio',
            name='id_resenia',
        ),
        migrations.AddField(
            model_name='resenia',
            name='anuncio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resenia', to='publiapp_api.Anuncio'),
            preserve_default=False,
        ),
    ]
