# Generated by Django 3.0.7 on 2020-10-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0013_auto_20200927_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='moneda',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticuloOcacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=800)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articuloOcacional', to='publiapp_api.Anuncio')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publiapp_api.Categoria')),
            ],
        ),
    ]
