# Generated by Django 3.0.7 on 2020-10-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0014_auto_20201004_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleanuncio',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='detalleanuncio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='publiapp_api.Categoria'),
            preserve_default=False,
        ),
    ]
