# Generated by Django 3.0.7 on 2020-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publiapp_api', '0015_auto_20201024_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeo',
            name='latitud',
            field=models.CharField(default=-13.517089, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubigeo',
            name='longitud',
            field=models.CharField(default=-71.978536, max_length=15),
            preserve_default=False,
        ),
    ]
